#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Eni.Banque.Android.Resource", IsApplication=true)]

namespace Eni.Banque.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int colorControlNormal = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int colorAccent = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int colorPrimary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int colorPrimaryDark = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int ic_launcher_background = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int fab_margin = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0015
			public const int action_create = 2131361813;
			
			// aapt resource value: 0x7f0a0016
			public const int action_customers = 2131361814;
			
			// aapt resource value: 0x7f0a0017
			public const int action_prefs = 2131361815;
			
			// aapt resource value: 0x7f0a0011
			public const int adapter_customer_fullname = 2131361809;
			
			// aapt resource value: 0x7f0a0005
			public const int clientform_nom = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int clientform_prenom = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int clientform_tel = 2131361799;
			
			// aapt resource value: 0x7f0a0010
			public const int customer_fullname_adapter = 2131361808;
			
			// aapt resource value: 0x7f0a0003
			public const int customerdetail_call = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int customerdetail_edit = 2131361796;
			
			// aapt resource value: 0x7f0a0000
			public const int customerdetail_firstname = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int customerdetail_lastname = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int customerdetail_phone = 2131361794;
			
			// aapt resource value: 0x7f0a0008
			public const int customerform_ok = 2131361800;
			
			// aapt resource value: 0x7f0a0012
			public const int customers_adapter = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int customers_adapter_fullname = 2131361811;
			
			// aapt resource value: 0x7f0a0014
			public const int customers_adapter_phone = 2131361812;
			
			// aapt resource value: 0x7f0a0009
			public const int customers_list = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int demo_activity_lifecycle = 2131361802;
			
			// aapt resource value: 0x7f0a000c
			public const int main_description = 2131361804;
			
			// aapt resource value: 0x7f0a000b
			public const int main_layout_relative = 2131361803;
			
			// aapt resource value: 0x7f0a000e
			public const int main_nav_customerform = 2131361806;
			
			// aapt resource value: 0x7f0a000d
			public const int main_nav_customers = 2131361805;
			
			// aapt resource value: 0x7f0a000f
			public const int main_nav_demo = 2131361807;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_customer_detail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_customer_form = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_customers = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_demo = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_main_relative = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int customer_fullname_adapter = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int customers_adapter = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int menu_main = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int baseline_add_24 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int baseline_view_list_24 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_launcher = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_launcher_foreground = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher_round = 2130837508;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070004
			public const int action_customerform = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int action_customers = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int action_prefs = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int app_short_name = 2131165185;
			
			// aapt resource value: 0x7f07000f
			public const int clientform_nom_label = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int clientform_prenom_label = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int clientform_tel_label = 2131165201;
			
			// aapt resource value: 0x7f07000c
			public const int customerdetail_call_label = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int customerdetail_edit_label = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int customerdetail_label = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int customerform_label = 2131165198;
			
			// aapt resource value: 0x7f07000a
			public const int customers_label = 2131165194;
			
			// aapt resource value: 0x7f070012
			public const int demo_label = 2131165202;
			
			// aapt resource value: 0x7f070009
			public const int main_customerform_link = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int main_customers_link = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int main_description = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int main_label = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int prefs_label = 2131165186;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int AppTheme = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
